sudo: required

services:
  - docker

jobs:
  include:
    - stage: Bake
      script:
      - docker build -t $DOCKER_USERNAME/maven_alpine3.5_jdk8:1.0 .
      - docker images
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker push $DOCKER_USERNAME/maven_alpine3.5_jdk8:1.0
      
    - stage: Test
      script:
      - docker run -itd $DOCKER_USERNAME/maven_alpine3.5_jdk8:1.0
      - docker ps -a
      - docker run --rm -it $DOCKER_USERNAME/maven_alpine3.5_jdk8:1.0 mvn --version
      - docker run --rm -it $DOCKER_USERNAME/maven_alpine3.5_jdk8:1.0  java -version
